const DESIGNER_DATA = [
    {
        "FULL NAME": "ANGELINE REBECCA GOMES",
        "PreferredName": "Angeline Gomes",
        "Designer Photo 3:4": "",
        "Personal Description": "Angeline enjoys designing thoughtful, simple products that tackle real problems, especially for children. Their playfulness echoes the joy she believes good design brings! Drawn to helping people, she has learnt that even small, intentional choices make people\u00e2\u20ac\u2122s lives just a little better. Sincerity and human connection shape both her life and design approach. In her free time Angeline enjoys baking, sewing, and spending time with people, which fills her with the joy she channels into her design.",
        "Icon Description": "Open hands reaching upwards represent my posture of surrender, strength, and growth. I\u00e2\u20ac\u2122ve been shaped and sustained by God\u00e2\u20ac\u2122s grace through these 4 years.",
        "Email": "angelinerebeccagomes@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "https://angelinegomes.myportfolio.com",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Yen Ching Chiuan",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "ASHLEY THONG WOON HUI",
        "PreferredName": "Ashley Thong",
        "Designer Photo 3:4": "",
        "Personal Description": "Ashley is a designer passionate about creating meaningful, user-centred experiences through service design and UI/UX. Her work is driven by curiosity, empathy, and a desire to bridge creativity with functionality. She enjoys understanding people\u00e2\u20ac\u2122s needs, uncovering insights, and transforming them into intuitive solutions. With a keen eye for detail and a strong belief in human-centred design, Ashley strives to create experiences that are both purposeful and visually compelling.",
        "Icon Description": "The curves reflect my approach to design - the absence of sharp corners symbolises my belief in creating human-centered experiences that prioritise ease and comfort. Just as the shape flows smoothly, I aim to navigate challenges with flexibility and understanding. ",
        "Email": "ashleythong.id@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "AW KER WEY",
        "PreferredName": "Aw Ker Wey",
        "Designer Photo 3:4": "",
        "Personal Description": "Ker Wey investigates the tensions inherent to our everyday experiences. Her practice tends to lean into areas of ambiguity, probing at the essence of things, and offering spaces to contemplate how we document and experience the world. She often explores the interplay of intuition and perception, tugging at the relationship between first impressions and afterthoughts. She is curious about inklings, patterns, and how we make sense of things, seeking to peruse the emotional subtext of it all.",
        "Icon Description": "Hand-cut, scanned, and then vectorised, this shape embodies my dedication to a handcrafted, intimate, and meticulous approach to design.",
        "Email": "awkerwey@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "awkw.cargo.site",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "CI",
        "Supervisor": "Hans Tan",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "CHA JU HYUN (Hannah)",
        "PreferredName": "Hannah Cha",
        "Designer Photo 3:4": "",
        "Personal Description": "Hannah (Ju Hyun) is a designer whose choices tend to be informed by the visions and principles of art, having had a love for visual art since young. This eventually evolved into a fascination with the orderliness of geometry, and the vibrancy and softness of undulating colours, which often manifest in her designs. She is drawn to exploring social and cultural experiences through the lens of design, delving into how we navigate the world and connect with others. Her work aims to find the intersection between form and meaning, distilling ideas into subtle yet resonant expressions.",
        "Icon Description": "",
        "Email": "hannahcjh7@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "CI",
        "Supervisor": "Christophe Gaubert",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "CHAN JIA YING",
        "PreferredName": "Chan Jia Ying",
        "Designer Photo 3:4": "",
        "Personal Description": "Jia Ying is a designer drawn to the subtleties of human experiences\u00e2\u20ac\u201dhow people navigate decisions and adapt in unseen ways. Specializing in service design, she uncovers overlooked behaviors while balancing diverse needs. Having worked in constraint-driven environments such as healthcare, she understands their complexities yet seeks to challenge limitations to drive meaningful change.\n\nWith a background in visual arts, Jia Ying is attuned to quiet resilience\u00e2\u20ac\u201dthe ways people persist, adapt, and find agency in adversity. This perspective shapes her approach, ensuring solutions that are not only functional but deeply resonate with those they serve. No matter the challenges ahead, she remains steadfast, committed to fighting for lasting impact.",
        "Icon Description": "My shape flows with quiet undulation - neither sharp nor static, but always shifting. As a generalist, I move across terrains with quiet strength and steady courage. There\u00e2\u20ac\u2122s softness here, but also resilience \u00e2\u20ac\u201d a form that grows into openness.",
        "Email": "jiayingchan5693@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "www.linkedin.com/in/chan-jia-ying",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "SS",
        "Supervisor": "Alistair Norris",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "CHAN MUN, DAWN",
        "PreferredName": "Chan Dawn",
        "Designer Photo 3:4": "",
        "Personal Description": "Dawn is a designer driven by curiosity, empathy, and a commitment to enhancing user experiences through thoughtful research. With a background in graphic and experience design, she embraces an open-minded approach to uncovering unexpected insights that shape more intuitive and impactful solutions. Her design process is rooted in understanding people\u00e2\u20ac\u201dtheir needs, behaviors, and emotions\u00e2\u20ac\u201densuring that every interaction feels meaningful. \n\nBeyond design, Dawn finds inspiration in indie music and books about life, always seeking new perspectives that enrich her creative thinking.",
        "Icon Description": "As a designer, I'm inspired by the moon, reflecting my passion for adaptability and growth. Like the moon\u00e2\u20ac\u2122s phases, I strive to understand the changing needs of people and the world. The crescent\u00e2\u20ac\u2122s curves symbolise my open-minded approach, embracing new perspectives to keep user experiences impactful.",
        "Email": "dawndesign01@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "CHAN SHAO KAYE",
        "PreferredName": "Chan Shao Kaye",
        "Designer Photo 3:4": "",
        "Personal Description": "Shao Kaye believes that design is a powerful tool for solving real-world problems while enhancing human experiences. With a focus on design research and service design, she places great importance on understanding users\u00e2\u20ac\u2122 needs, behaviours and emotions to uncover insights that inform impactful designs.\n\nHer work revolves around fostering meaningful connections\u00e2\u20ac\u201dbe it between people, their surroundings, or the things they interact with. Driven by empathy, she strives to design solutions that resonate with people on a personal level and create experiences that leave a positive impact on users and the world around her.",
        "Icon Description": "My design approach focuses on creating meaningful, impactful experiences that merge empathy with practicality. The structured form of the shape reflects functionality, while its rounded edges convey the human touch I strive to incorporate.",
        "Email": "chanshaokaye@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "https://chanshaokaye.framer.website/",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/chanshaokaye/",
        "Which of these links you want on your Archive profile": "Linkedin + portfolio",
        "Which of these links you want on your Gradsite profile (max 2)": "Linkedin + portfolio",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "CHAN ZHENG QI ZOEY",
        "PreferredName": "Zoey Chan",
        "Designer Photo 3:4": "",
        "Personal Description": "Design is serious business. Which is exactly why Zoey refuses to take it seriously. The most powerful ideas aren't the ones that blend in, but rather, they're the ones that make you do a double take, and leave you wondering why things are the way that they are. Because if something makes you stop and laugh, you\u00e2\u20ac\u2122ll never forget it.\n\nZoey designs with color, chaos, and fun, pushing back against the creeping weight of monotony.Whimsy is her way of reminding everyone that the world doesn't need more rules, it needs more fun.\n\nOutside the studio, Zoey functions almost exclusively on coffee and freelances as an illustrator, branding, and graphic designer.",
        "Icon Description": "I hope to infuse fun and play into every design, evoking a warmth and approachability that connects deeply and sparks emotions.",
        "Email": "zoeychan2002123@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "https://readymag.com/u3435791990/4367625/",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Donn Koh",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "CHEN YUETING (Jay)",
        "PreferredName": "Jay Chen",
        "Designer Photo 3:4": "",
        "Personal Description": "",
        "Icon Description": "",
        "Email": "",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "SS",
        "Supervisor": "Patrick Chia",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "EDA YASMIN BINTE ASNI",
        "PreferredName": "Eda Yasmin",
        "Designer Photo 3:4": "",
        "Personal Description": "Eda is a designer who believes that small, thoughtful ideas can make a big difference. Through design, she has learned to notice what often goes unseen and to create with care. She\u00e2\u20ac\u2122s especially drawn to projects that make everyday life a little easier and more meaningful.\n\nOutside of design, Eda spends a lot of time drawing fat cats, crocheting little things, and hanging out with loved ones. These personal routines often feed into her work, reminding her that design can be quiet and grounded. Not everything has to be bold to matter.\n\nFor her, design isn't about finding perfect solutions. It\u00e2\u20ac\u2122s about staying curious, paying attention, and making things that matter to someone.",
        "Icon Description": "With three blobs emerging from a base, my shape represents growth, transformation, and balance. This shape represents the evolution of my creativity, adaptability, and purpose as I blossom into the person I\u00e2\u20ac\u2122m meant to become.",
        "Email": "edayasmin3@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Song Kee Hong",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "EU HUI SIN",
        "PreferredName": "Eu Hui Sin",
        "Designer Photo 3:4": "",
        "Personal Description": "Hi, I'm Hui Sin! Design makes me more observant, curious, and attuned to the little things people overlook. I'm drawn to where functionality, meaning, and exploration meet, where objects and experiences tell stories and spark conversations.  \n\nI use design to challenge norms, reimagine everyday objects, and bring people together in unexpected ways. More than solving problems, I see design as a way to ask questions, reflect on behavior, and shape how we experience the world.",
        "Icon Description": "The sharp angle represents my drive for deep insights, flowing into a wave that sparks questions and connects people, focusing on the little things people overlook.",
        "Email": "huisin.eu@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "CI",
        "Supervisor": "Janghee",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "GAN JIE LIN",
        "PreferredName": "Gan Jie Lin",
        "Designer Photo 3:4": "",
        "Personal Description": "To Jie Lin, design is craft with purpose. Seeing herself first and foremost as a craftsman before a designer, she enjoys working with her hands and finds meaning in the making of things. She often brings an expressive and personal touch to her works, but always considers the practicality and the functionality of the outcomes that she designs. In her perspective, good design is meant to live in people's hands, where her biggest satisfaction comes from when people interact with what she creates. Through an honest and grounded process, and an eye for detail, she creates her works with intention. ",
        "Icon Description": "Having worked with crafts for so long, I find the most comfort when working with my hands, allowing them to almost 'mold' the final outcome.",
        "Email": "ganjielin99@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "https://ganjielin99.wixsite.com/my-site",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Donn Koh",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "GERALDINE TONG XIN YIN",
        "PreferredName": "Geraldine Tong",
        "Designer Photo 3:4": "",
        "Personal Description": "Geraldine Tong is a designer driven by curiosity, always seeking to understand why people think the way they do. To her, design is about more than just solving problems. It is about questioning without prejudice, digging deeper beyond face value assumptions, and creating experiences that truly resonate with people. Trained in both product and UIUX design, she enjoys bridging the physical and digital, designing solutions that make life smoother, smarter and more meaningful.",
        "Icon Description": "My shape, whether seen as bubbles or clouds, reflects the soft, imaginative spirit I bring to my work. I believe design shouldn't just be innovative. It should be approachable, comforting and easy for everyone to connect with.",
        "Email": "Geraldinetong.id@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "https://geraldinetongportfolio.framer.website/",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "GERRICA EPONINE TAN FEI",
        "PreferredName": "Eponine Tan",
        "Designer Photo 3:4": "",
        "Personal Description": "Eponine is a designer who delights in creating work that brings joy to others. With a background in Visual Arts, her designs blend simplicity and elegance with a playful, vibrant touch. An empathetic and thoughtful creator, she values connection and seeks to make a meaningful impact through design. With a passion for graphic design and UI/UX, she believes that even the smallest design choices can improve lives in subtle yet significant ways.",
        "Icon Description": "My shape represents a balance between playful creativity and simplicity, reflecting the way I approach design\u00e2\u20ac\u201dwith a lightheartedness that sparks joy and invites meaningful connection.\n\n\n\n\n\n\n\n",
        "Email": "eponine.tan@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "GOH BING JUN",
        "PreferredName": "Goh Bing Jun",
        "Designer Photo 3:4": "",
        "Personal Description": "Hi, I\u00e2\u20ac\u2122m Bing Jun. As an industrial designer, I enjoy proving myself wrong. \n\nThat means striving for constant self-improvement and daring to push boundaries. I am deeply interested in designing things that just feels right and simply works without needing an instruction manual. \n\nTo me, design is all about solving problems in an elegant manner that people never seem to take notice of, even when its obvious.",
        "Icon Description": "The future is shaped by those who ask, \u00e2\u20ac\u02dcWhat if?\u00e2\u20ac\u2122. The negative circle in my shape symbolizes the limitless expansion of horizons into the unknown, grounded by a methodical yet bold approach that combines creative exploration with the grit to bring ideas to life.",
        "Email": "bengoh99@hotmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/goh-bing-jun-id99/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Song Kee Hong",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "HUANG KAI XING",
        "PreferredName": "Huang Kai Xing",
        "Designer Photo 3:4": "",
        "Personal Description": "Kai Xing once stared at an ordinary remote control and wondered\u00e2\u20ac\u201dwhat happens within the objects he interacts with every day? That curiosity led him to dismantle anything he could get his hands on, studying what goes into making a product. That moment shaped the way he approaches design and everyday interactions\u00e2\u20ac\u201dby uncovering what lies beyond the obvious, the intangible aspects of daily life.\n\nA designer and a tinkerer at heart, Kai Xing is fascinated by the inner workings of everyday objects, often taking them apart, modifying, or even rebuilding them just to understand their mechanics. Whether it\u00e2\u20ac\u2122s repurposing discarded electronics, experimenting with materials, or refining everyday tools, he finds excitement in hands-on exploration. For him, design is not just about function and form\u00e2\u20ac\u201dit\u00e2\u20ac\u2122s about discovering new possibilities hidden within the familiar.",
        "Icon Description": "The shape balances utilitarian functionality with personal identity in the form of my initials. Its structured form and defined edges symbolize my appreciation for distinctiveness and reflect how I blend practicality with a unique, bold presence in all my endeavors.",
        "Email": "huangkaixing20@outlook.sg",
        "Instagram": "",
        "Behance": "https://www.behance.net/huangkaixing",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "www.linkedin.com/in/huang-kai-xing",
        "Which of these links you want on your Archive profile": "LinkedIn",
        "Which of these links you want on your Gradsite profile (max 2)": "LinkedIn",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Yen Ching Chiuan",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "ISABELLE BRIGITTE KIRKWOOD",
        "PreferredName": "Isabelle Kirkwood",
        "Designer Photo 3:4": "",
        "Personal Description": "Driven to design with intention, Isabelle seeks to create experiences that resonate while offering a fresh lens through which to view the world. Blending her roles as a service designer and visual artist, she applies in-depth user research, behavioral analysis and a visual approach to uncover the narratives that shape meaningful experiences. Outside of design, Isabelle finds comfort in quiet observation through sketching the everyday in her pocket-sized sketchbook, or cycling through new terrain to keep herself curious.",
        "Icon Description": "Just like my shape, I like all things dynamic. To me, change, transformation and the ability to adapt is central to both life and design.",
        "Email": "isabelle.kirkwood88@gmail.com",
        "Instagram": "",
        "Behance": "https://www.behance.net/isabellkirkwoo1",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "SS",
        "Supervisor": "Alistair Norris",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "JARED LIM",
        "PreferredName": "Jared Lim",
        "Designer Photo 3:4": "",
        "Personal Description": "Jared sees design as a catalyst for different outcomes. He enjoys exploring various approaches and combining methods to produce novel results. He looks for patterns in strange experiments and constantly seeks fun, less serious ways to stay creative.\n\nAside from product design, he conducts research experiments, and sometimes graphic design finds him in unexpected ways. Outside of work, he writes stories and builds concepts for his personal world-building hobbies.\n\nHis dream is to travel and be inspired by different design styles around the world. This fuels his passion and joy for working with design.",
        "Icon Description": "Just like my shape, leaving some things incomplete brings in more opportunities to complete.",
        "Email": "limjared2@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Clement Zheng",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "JEROME JIMMY WONG",
        "PreferredName": "Jerome Wong",
        "Designer Photo 3:4": "",
        "Personal Description": "",
        "Icon Description": "",
        "Email": "",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "SS",
        "Supervisor": "Alistair Norris",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "JOSHUA LIM JIAJUN",
        "PreferredName": "Joshua Lim",
        "Designer Photo 3:4": "",
        "Personal Description": "A thinker at heart, Joshua is obsessed with rationalizing the meaning and purpose behind everything. His personal fascination with abstract and philosophical ideas is married with a pragmatic and logical approach to work, culminating in a curiosity and drive to turn visionary concepts of the future into reality. He believes that in introducing new and often intimidating ideas, designers play a crucial role as the bridge between innovation and familiarity, to connect foreign and exciting concepts with what we already know, and making new possibilities accessible to all.",
        "Icon Description": "The role of design is to bring new and often intimidating ideas with a familiar and approachable touch.",
        "Email": "limjiajunjoshua@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "CI",
        "Supervisor": "Christophe Gaubert",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "JOSHUA TAN JIANHAO",
        "PreferredName": "Joshua Tan",
        "Designer Photo 3:4": "",
        "Personal Description": "Playful, fun and engaging, these are the things that intrigue Joshua when it comes to design. From playing with buildable toy blocks and board games as a kid, it developed into a hobby and passion in designing his own things of play like his own board games.\n\nThis passion also carries over to his designs, making places or products to be played with, to be appreciated, to be engaged with. He finds joy in bringing others joy and thus strives for excellence in his work, paying attention to the tiny details that make up the whole. \n\nIn his free time he also enjoys sculpting models or making miniatures. ",
        "Icon Description": "I'm intrigued by grids and blocks that fit together like a puzzle.  I love piecing things together in a playful way, seeing smaller components come together to achieve bigger goals in fun and functional ways.",
        "Email": "joshtanjh@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Clement Zheng",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "KOH MIN XIANG",
        "PreferredName": "Koh Min Xiang",
        "Designer Photo 3:4": "",
        "Personal Description": "Min Xiang is a reflective and intentional thinker who seeks meaning in both life and design. He approaches the world with a quiet curiosity, valuing the slow, deliberate process of discovery. His design philosophy is rooted in hands-on experience, where making and reflecting are intertwined.\n\nHe finds beauty in the small, often overlooked moments\u00e2\u20ac\u201dcapturing them through journaling and thoughtful observation. This meditative connection between hand and mind not only shapes his creative practice but also nurtures his personal growth and sense of consciousness.\n\nMin Xiang\u00e2\u20ac\u2122s work reveals a person who designs not just to solve, but to understand, connect, and grow\u00e2\u20ac\u201dsomeone who sees design as a dialogue between the inner self and the external world.",
        "Icon Description": "I often swim in abstract thoughts, much like a roller coaster. This shape represenes of my mind, reflecting the fluidity and imagination of my thinkingts the twists and curv.",
        "Email": "minxiangkoh@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "minxiang.myportfolio.com/",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Christian Boucharenc",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "KRISTY TAN WEI QI",
        "PreferredName": "Kristy Tan",
        "Designer Photo 3:4": "",
        "Personal Description": "From an early age, Kristy found comfort in video games, movies, and anime, and they have been her main sources of inspiration ever since.\n\nTo her, design is about seamlessly blurring the boundaries between reality and fantasy, where it is an invitation to experience a world where people can escape to. Creating designs that resonate deeply with both the heart and the senses.\n\nOutside the world of design, she enjoys exploring the beauty industry and tinkering with custom mechanical keyboards.",
        "Icon Description": "Design is about blending the boundaries between reality and imagination, creating a connection that resonates deeply with both the heart and the senses.",
        "Email": "kvistychomelle@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "https://vyndxart.wixsite.com/portfolio/visualdesign",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/kristy-tan-wq/",
        "Which of these links you want on your Archive profile": "Linkedin + Email",
        "Which of these links you want on your Gradsite profile (max 2)": "Portfolio + Linkedin",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Donn Koh",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "KWAN JIA CHEN SUZIE",
        "PreferredName": "Suzie Kwan",
        "Designer Photo 3:4": "",
        "Personal Description": "When things feel disconnected and overwhelming, good design facilitates clarity, intuitive experiences, and genuine connections.\n\nSuzie focuses on service design, UI/UX, and research, with a strong emphasis on understanding user behavior, simplifying complexity, and designing with empathy. She enjoys dissecting what makes a system work (or not) and finding ways to improve it for better experiences. This mindset has shaped her curiosity and perspective, allowing her to adapt to each unique challenge and craft solutions that are both functional and meaningful. The goal is always to create the best possible outcomes, regardless of the design medium.",
        "Icon Description": "My shape reflects the balance I seek in everything I do. It\u00e2\u20ac\u2122s about the coexistence of structure and fluidity, representing how I navigate between clarity and exploration, always adapting, always evolving.",
        "Email": "suzie.kjc@gmail.com",
        "Instagram": "",
        "Behance": "behance.net/suziekjc",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/suziekjc/",
        "Which of these links you want on your Archive profile": "Linkedin + behance",
        "Which of these links you want on your Gradsite profile (max 2)": "Linkedin + behance",
        "Project Title ( 1 Liner)": "NOM",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "LAU RUI XUAN",
        "PreferredName": "Lau Rui Xuan",
        "Designer Photo 3:4": "",
        "Personal Description": "Have you ever wondered too much...? Probing at existence, Rui Xuan toys with what can be observed, turning them into objects for conversation through design principles.\n\nHer craft lies in creating stories for entities that exist in the periphery\u00e2\u20ac\u201doften fleeting\u00e2\u20ac\u201dgiving them a platform to be seen, heard, and felt through design.\n\nShe seeks to connect with people through familiarity, using design as a medium to reframe and possibly relive the everyday.",
        "Icon Description": "A person made out of 3 rectangles, or 3 rectangles made by a person...? This shape reflects my design approach - doing the most with the least!",
        "Email": "lauruixuan@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "https://readymag.website/u1579269952/rxrxrx/",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/rui-xuan-lau-16a156239/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "CI",
        "Supervisor": "Hans Tan",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "LEE SI YING SHARON",
        "PreferredName": "Sharon Lee",
        "Designer Photo 3:4": "",
        "Personal Description": "Sharon is a UI/UX designer passionate about crafting user-centric experiences. She specializes in designing intuitive, functional and visually compelling solutions. By blending thoughtful design principles with a deep understanding of user needs, she optimizes digital interfaces, enhances service touchpoints, and tackles complex challenges with innovative solutions.\n\nHer strength lies not only in delivering polished outcomes but also in the process itself. Sharon believes that a good design is more than a solution; it\u00e2\u20ac\u2122s a perpetual interaction between users, systems, and their environment.",
        "Icon Description": "I'm a designer who values a balance between structure and flow, approaching challenges with creativity and flexibility. ",
        "Email": "sharonleesiying@gmail.com",
        "Instagram": "",
        "Behance": "behance.net/sharonlsy",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/sharonlsy/",
        "Which of these links you want on your Archive profile": "Linkedin + Behance",
        "Which of these links you want on your Gradsite profile (max 2)": "Linkedin + Behance",
        "Project Title ( 1 Liner)": "pre-sent.",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "LIM YOU GUANG BRYCE",
        "PreferredName": "Bryce Lim",
        "Designer Photo 3:4": "",
        "Personal Description": "Bryce Lim explores the expressive potential of shaping materials and production processes, whether industrial or traditional, digital or handcrafted. His work is driven by experimentation and supported by a meticulous approach to documentation, often straddling the boundaries between art and design. For Bryce, making is a dialogue between the mind, hand, and material - to allow it to speak for itself, or to challenge its nature. As a result, each design is approached as more than just functional; it is considered for its presence, gesture, and character. Looking ahead, he hopes to continue developing this approach through the design of furniture and objects.",
        "Icon Description": "I\u00e2\u20ac\u2122ve consistently been drawn, perhaps instinctively, to mushroom-like forms - something my peers often point out. As someone interested in designing furniture and objects, the silhouette also naturally reminds me of lamps, making it a simple blend of both influences.",
        "Email": "limbryce12@gmail.com",
        "Instagram": "",
        "Behance": "behance.net/limbryce",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/bryce-lim-148455126/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Patrick Chia",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "Daniel values practicality and functionality in design, always focused on creating solutions that are efficient and reliable.",
        "PreferredName": "Loh Yi Zhi",
        "Designer Photo 3:4": "",
        "Personal Description": "Yi Zhi is a designer that enjoys learning, understanding complex problems,\nand developing practical solutions. His passion lies in human-centered design,\nparticularly in service design and healthcare products, where the focus is on creating\nmeaningful and impactful user experiences.",
        "Icon Description": "Like a rectangle, I value practicality and functionality in design, always focused on creating solutions that are efficient and reliable.",
        "Email": "yizhiloh@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/daniellohyizhi/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "LOW ZHI YANG DILON",
        "PreferredName": "Dilon Low",
        "Designer Photo 3:4": "",
        "Personal Description": "Dilon is a nature lover passionate about sustainability and conservation. He strives to use design as a tool to address environmental issues that are becoming increasingly prevalent. His acute sense of aesthetic helps him to discern the right balance between aesthetic and function within a piece of work.  ",
        "Icon Description": "Live your best life wherever the road may take you. Staying calm under pressure, I navigate the complexities of design while maintaining a steady focus on the end goal. ",
        "Email": "DilonLow@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/dilonlow/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "CI",
        "Supervisor": "Janghee",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "LUMNA CHITRAKAR",
        "PreferredName": "Lumna Chitrakar",
        "Designer Photo 3:4": "",
        "Personal Description": "Lumna is a designer who believes that simplicity is the ultimate sophistication\u00e2\u20ac\u201da philosophy that deeply influences her approach to design. For her, simplicity means stripping away the unnecessary, allowing the core essence of a concept to emerge in its most refined form. It\u00e2\u20ac\u2122s about creating elegant solutions that are both functional and visually compelling, without overwhelming the senses. Captivated by the worlds of video games and movies, Lumna draws inspiration from their imaginative storytelling and striking visuals. These mediums have shaped her creative process, fueling her desire to design experiences that are immersive and meaningful. With a background in visual effects and motion graphics, Lumna brings a fresh, unique perspective to her work, blending technical skill with artistic intuition.Her curiosity leads her to embrace moments of sonder, taking time to reflect on the lives and perspectives of those around her, finding inspiration in the stories that often go unnoticed. This deep understanding of others fuels her drive to create innovative solutions that resonate on a personal level with those who experience her designs.",
        "Icon Description": "Just like waves, design should be both strong and fluid \u00e2\u20ac\u201d grounded and purposeful yet with room for flexibility and creativity.",
        "Email": "",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/lumna-chitrakar/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "MUHAMMAD HAZIQ BIN ROSLANY",
        "PreferredName": "Haziq Roslany",
        "Designer Photo 3:4": "",
        "Personal Description": "\nHaziq doesn\u00e2\u20ac\u2122t design objects. He designs the quiet spaces between actions where hands meet objects, bodies meet space, and routines become rituals. With an ethnographer's patience and a poet's precision, he deciphers what others overlook: the hesitation before grasping, the lean into emptiness, the unspoken choreography of shared spaces. These become his raw material. His work whispers fluidity where others force, thoughtfulness where others compromise. No loud statements, just forms that adapt to real behavior. The best design, he believes, isn\u00e2\u20ac\u2122t seen but felt. It\u00e2\u20ac\u2122s the sudden realization that life could\u00e2\u20ac\u2122ve been this effortless all along.",
        "Icon Description": "I am someone who constantly seeks balance and precision. The curved triangle represents my journey, steep and challenging yet driven by determination and growth. The circle at the tip symbolizes my pursuit to perfection and the wholeness I aim to achieve. ",
        "Email": "haziqroslany@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "https://haziiqroslany.myportfolio.com/",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/haziiqroslany-/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "ONG ZHI KAI, DOUGLAS",
        "PreferredName": "Douglas Ong",
        "Designer Photo 3:4": "",
        "Personal Description": "The best designs don\u00e2\u20ac\u2122t just function well\u00e2\u20ac\u201dthey evolve with their users.\n\nDouglas thrives on uncovering the unseen\u00e2\u20ac\u201dbridging the gap between user, service experience, and product with a keen eye for context. By blending rigorous research with inventive experimentation, his multi-perspective approach uncovers hidden challenges and transforms them into opportunities for improvement. To him, the interweaving of various design disciplines are naturalistic and often reflects a real world perspective.\n\nWith a background in product design and photography, he brings together a wealth of experience from the appreciation and execution of visual arts, to a honed sensitivity towards the balance of form and function.",
        "Icon Description": "Douglas believes in design that uplifts \u00e2\u20ac\u201d balanced, human, yet precise.",
        "Email": "ozkdouglas@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "https://douglas-ong-design.webflow.io/",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/douglas-ong-zk/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Song Kee Hong",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "PANG XUE LE CHERYL",
        "PreferredName": "Cheryl Pang",
        "Designer Photo 3:4": "",
        "Personal Description": "Cheryl is a designer who focuses on creating intuitive, functional experiences that make life easier. She enjoys distilling intricate problems into seamless solutions, always prioritizing usability and user needs. Her passion for UX/UI design lies in translating complex human behaviors into thoughtful, user-centered interactions.",
        "Icon Description": "My shape represents the convergence of a mountain and a wave, illustrating my  grounded nature, balanced with a readiness to adapt and evolve with every design project.",
        "Email": "cheryl.pangxl@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "https://portfolio-3c490a.webflow.io/",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/cheryl-pang-50288924a/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "PATRICIA TANTRASARI SETIAWAN",
        "PreferredName": "Patricia Setiawan",
        "Designer Photo 3:4": "",
        "Personal Description": "Understanding people\u00e2\u20ac\u2122s stories, perspectives, and the way they interact with the world, Patricia shapes the way people connect, not just with interfaces but with the essence of a brand itself. For her, design is about uncovering the emotions, unseen needs, and hidden influences that shape the way we live and engage with our environment. Every design begins with an exploration of what truly moves people, an understanding that informs both user experience and the stories brands tell. Patricia creates experiences that quietly becomes a part of everyday life, with designs that feel both natural and meaningful.",
        "Icon Description": "Just like the flow of my shape, I'm all about finding the balance between structure and flexibility. I love diving deep into the user experience while staying open to adaptation, following a design process that's grounded but never rigid. ",
        "Email": "patriciasetiawan784@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/patricia-setiawan-838b31255/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "RACHAEL ANNE LEE HUI TING",
        "PreferredName": "Rachael Anne",
        "Designer Photo 3:4": "",
        "Personal Description": "As a trained Industrial Designer, Rachael has the passion to create ideas that improve the lives of others. She is interested in user experience and storytelling, seeing them as essential to making designs more intuitive, engaging, and emotionally resonant. She strives to design solutions that not only meet functional needs but also create meaningful connections with users, enhancing their daily experiences.",
        "Icon Description": "In design, I am captivated by the elegance of simple geometry. From afar, the shape might appear ordinary. But up close, subtle details such as soft curves, intricate patterns, or slight shifts in proportion reveal a hidden personality.",
        "Email": "rachanneleeht@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/rachael-anne-lee/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "SEAH JUN HAO REYNARD",
        "PreferredName": "Reynard Seah",
        "Designer Photo 3:4": "",
        "Personal Description": "Reynard believes in the honesty of design, that it should be intuitive and emotive regardless of the medium. His works often start from understanding and ideas, driven by the need to uncover the meaning behind a design: why it exists, what it communicates, and the emotions that it evokes within people. Yet, he appreciates ideas that draw from beneath the common perception and attempts to read between the lines to uncover hidden meanings within ambiguity, letting intuition lead him to simple, honest yet unexpected outcomes that users can feel for.",
        "Icon Description": "To me, I believe that the human element is the most important element in design. It touches on the senses and emotions, through observation and empathy. To design for the human is to be intuitive, emotive, and nothing short of that.",
        "Email": "rynrd.design@gmail.com",
        "Instagram": "",
        "Behance": "https://www.behance.net/rynrd",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/rynrd/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Clement Zheng",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "SHERYL CHEONG",
        "PreferredName": "Sheryl Cheong",
        "Designer Photo 3:4": "",
        "Personal Description": "Sheryl embraces creativity through hands-on exploration, finding excitement in crafting, building, and experimenting with new techniques. Her work is driven by curiosity, constantly evolving as she discovers and refines new skills. She engages deeply with materials, learning from them and allowing their unique qualities to influence her designs. She balances creativity with practicality, ensuring that each project is both expressive and functional. With an ever-growing collection of hobbies and a love for making, she thrives on the process of learning and creating. Looking ahead, she hopes to keep expanding her skills, combining diverse techniques to create work that is both inventive and uniquely her own.",
        "Icon Description": "My shape represents who I am \u00e2\u20ac\u201d a creative, fun and thoughtful person who brings passion for people into everything I do. ",
        "Email": "sheryl.cheong170601@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "SOPHIA CHIN YING TING",
        "PreferredName": "Sophia Chin",
        "Designer Photo 3:4": "",
        "Personal Description": "Sophia\u00e2\u20ac\u2122s approach is deeply informed by her environment, drawing inspiration from personal artefacts tied to everyday rituals. Keen observation allows her to uncover subtle beauty and wonder in the ordinary, a sensibility that brings warmth to her work.\n\nSophia embraces a hands on, material led process, never afraid to get messy or dive into laborious work. Guided by mindfulness, her practice considers not just how objects are made, but how they are experienced. For her, the process of making is just as meaningful as the final outcome.",
        "Icon Description": "This fuzzy form is an ode to the things I love: soft, organic shapes with a hint of eccentricity. It\u00e2\u20ac\u2122s born from my affection for all things cute and full of character \u00e2\u20ac\u201d a little odd, but always endearing. Like me, it doesn\u00e2\u20ac\u2122t take itself too seriously. ",
        "Email": "sophiphiachin@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/sophia-chin-bb5a97220/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "CI",
        "Supervisor": "Hans Tan",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "SOON WEI YA JASMINE",
        "PreferredName": "Jasmine Soon ",
        "Designer Photo 3:4": "",
        "Personal Description": "Branding & UI/UX Designer \n\nEvery design starts with a meaningful conversation: one that helps build, nourish and redefine the idea into something that fits for the client and people\u00e2\u20ac\u2122s lives. \n\nHey there! Jasmine designs simple interfaces with a passion for better design. By focusing on how people navigate decisions, she delves into understanding user & company needs, co-creating solutions for a more intuitive UI tool. Jasmine had the opportunity to design branding for SG60 x GBTB for 200 elderly volunteers from care organisations, amongst other design opportunities. Let\u00e2\u20ac\u2122s bring ideas to life:)  \n",
        "Icon Description": "I believe that design can be simple, yet seamless. Every project starts with a meaningful conversation between client and end user.",
        "Email": "jasmine7046@gmail.com",
        "Instagram": "",
        "Behance": "https://www.behance.net/jasminesoon",
        "Portfolio": "https://jasminesoon.framer.website/",
        "Portrait": "",
        "LinkedIn": "www.linkedin.com/in/jasmine-soon-b41772234",
        "Which of these links you want on your Archive profile": "Linkedin + Portfolio",
        "Which of these links you want on your Gradsite profile (max 2)": "linkedin + Portfolio",
        "Project Title ( 1 Liner)": "Medmo",
        "Cluster": "non-thesis ",
        "Supervisor": "non-thesis ",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "TAN DIAN CHONG DYLAN",
        "PreferredName": "Dylan Tan",
        "Designer Photo 3:4": "",
        "Personal Description": "Dylan is a hands-on creator who thrives when his ideas come to life through making it with his own two hands.With a deep appreciation for wood; its organic grain, rugged knots, and natural imperfections, first ignited his passion for materials and form. To him, these \"flaws\" should be celebrated, revealing the quiet beauty hidden in everyday nature.  \n\nThis reverence for raw craftsmanship now fuels his innovative approach to product design. Whether creating a prototype by hand or coding an interactive interface, Dylan obsesses over the dialogue between physical and digital experiences. He believes the most memorable designs emerge when technology feels as warm and intentional as handcrafted objects. \n\nFor him, interaction design isn\u00e2\u20ac\u2122t just about functionality, it\u00e2\u20ac\u2122s about creating emotional resonance. He designs to surprise, delight, and connect, blurring boundaries until users forget where the physical ends and the digital begins. ",
        "Icon Description": "Design to me has always been a push and pull, just like the waves that come and go. I always end up coming back to it due to my love for creation no matter how frustrating it is. ",
        "Email": "dylantandc22@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "www.linkedin.com/in/dylantandianchong",
        "Which of these links you want on your Archive profile": "Linkedin",
        "Which of these links you want on your Gradsite profile (max 2)": "linkedin ",
        "Project Title ( 1 Liner)": "FighTeng",
        "Cluster": "Non-thesis ",
        "Supervisor": "Dr Yen",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "TAN JUN JIE, WESLEY",
        "PreferredName": "Wesley Tan",
        "Designer Photo 3:4": "",
        "Personal Description": "Wesley is a designer who brings ideas to life.\n\nHe is deeply fascinated by cutting-edge technology and contemporary design. Through his design journey, he has developed a strong appreciation for the ability to connect the dots\u00e2\u20ac\u201dbetween concepts, people, and experiences. This approach allows him to create thoughtful and impactful work that resonates with others.\n\nDesign has become a way for Wesley to express ideas and emotions without boundaries. It has shaped the way he thinks, communicates, and solves problems. His passion lies in crafting products that leave a lasting impression and bring meaningful value to people.",
        "Icon Description": "I\u00e2\u20ac\u2122m passionate about transforming ideas into reality. I thrive on connecting the dots between creativity and functionality, turning concepts into tangible outcomes.",
        "Email": "westanjj@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/westanjj/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "TENG XIN YUN",
        "PreferredName": "Teng Xin Yun",
        "Designer Photo 3:4": "",
        "Personal Description": "Xin Yun is a designer with a keen interest in user experience and human behaviour. She enjoys understanding how people think and act, using these insights to create thoughtful and effective designs. Through various projects, she has sharpened her observational skills, allowing her to uncover patterns and translate them into meaningful solutions.\n\nHer approach balances structure with creativity, focusing on clarity and ease of use. Xin Yun values adaptability and critical thinking, ensuring her designs are not only functional but also intuitive and engaging. She is committed to creating designs that feel natural and resonate with users.",
        "Icon Description": "The shape\u00e2\u20ac\u2122s flowing lines and soft curves showcase my sensitivity and adaptability towards design. It reflects my flexible approach to creativity, embracing change and expressing myself through calm and thoughtful design.",
        "Email": "xinyunxy@gmail.com",
        "Instagram": "",
        "Behance": "https://www.behance.net/tengxinyun",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/tengxinyun/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "TEO SWEE YIN",
        "PreferredName": "Teo Swee Yin",
        "Designer Photo 3:4": "",
        "Personal Description": "Swee Yin is a designer with a diverse background, trained in industrial and product design, and experienced in graphic and service design. With a strong curiosity about human behaviour, she focuses on creating seamless, intuitive experiences that address user needs and enhance interactions.\n\nHer multidisciplinary approach blends creativity with research, exploring how people engage with both digital and physical environments. As an experience designer, Swee Yin is dedicated to ensuring that every design decision enhances the user journey, balancing functionality, accessibility, and visual appeal. Moving forward, she aims to push the boundaries of experience design, shaping interactions that leave a lasting impact.",
        "Icon Description": "I'm a designer on a journey up the mountain of creativity. Inspired to grow, adapt and innovate with each step.",
        "Email": "teo_sweeyin@hotmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/teosweeyin/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "",
        "Supervisor": "",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "TEO TZE YANG",
        "PreferredName": "Teo Tze Yang",
        "Designer Photo 3:4": "",
        "Personal Description": "Tze Yang enjoys conversing with people from all walks of life, honing a strong sense of empathy across his extensive interactions. Specializing in service design, he believes that this empathy, accompanied by some practicality, goes a long way in creating sustainable and effective solutions.\n\nBelieving in being an all-rounder, he hopes to develop himself in other areas of interest ranging from game development to photography. It is his fervent wish to continue making meaningful connections, to continue to apply his craft, and to continue learning from others.",
        "Icon Description": "I'm an introspective person who enjoys finding fun in the mundane, meaning in the obtuse, and solutions in the most unlikely situations. First impressions count, but there's often more than meets the eye.",
        "Email": "tzeyangteo@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "www.linkedin.com/in/teotzeyang",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "SS",
        "Supervisor": "Patrick Chia",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "TING ZHONG XUN (Jayden)",
        "PreferredName": "Jayden Ting",
        "Designer Photo 3:4": "",
        "Personal Description": "Jayden is a designer who thrives on the balance between structure and disruption. Whether in function or aesthetics, his work is rooted in creating order, only to challenge it. By pushing beyond conventions and redefining boundaries, he uncovers new possibilities that feel both innovative and deeply connected to our familiar reality. His design approach is a continuous dialogue between the known and the unknown, shaping experiences that are both unexpected and intuitive.\n\n\n\n\n\n\n\n\n",
        "Icon Description": "My design philosophy is grounded in structured forms that open up limitless possibilities, inviting users to explore and engage beyond the obvious. My shape adheres to a defined matrix while remaining open to your most imaginative interpretations.",
        "Email": "jaydentingdesign@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "CI",
        "Supervisor": "Christophe Gaubert",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "WANG YIXIAN (Jasmine)",
        "PreferredName": "Wang Yixian",
        "Designer Photo 3:4": "",
        "Personal Description": "Yixian seeks harmony between craftsmanship, materials, and design, finding joy in the journey of making and bringing ideas to life. Her work grows from hands-on exploration. She also works closely with materials, paying attention to their natural traits, learning from them, and letting them shape her projects. \n\nShe blends creativity with practicality, ensuring every piece feels meaningful, not just useful. By collaborating with materials, she creates work that honors both their natural qualities and her artistic vision. In the future, she aims to use traditional knowledge with modern design language, crafting pieces that feel rooted in culture yet uniquely her own.  ",
        "Icon Description": "The flower reflects my name and symbolizes my deep connection to nature, from which I draw inspiration.Just as the flower embodies the softness and gentleness of nature, I strive to bring these qualities into my work.",
        "Email": "yixianwang.design@gmail.com",
        "Instagram": "",
        "Behance": "https://www.behance.net/yixianwang",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/yixian-wang/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Patrick Chia",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "WANG YU WEI",
        "PreferredName": "Wang Yu Wei",
        "Designer Photo 3:4": "",
        "Personal Description": "Yu Wei is driven by a fascination with how people interact, with products, systems, and each other. He is drawn to the subtle ways interaction can quietly shape behaviour, turning ambiguity into intuitive experiences. To him, meaningful interactions go beyond simply guiding users; they create moments of connection and understanding through shared experiences. This belief grounds his approach to design: not just as an exercise in form or function, but as a way to be empathetic and create lasting impact in people\u00e2\u20ac\u2122s lives.",
        "Icon Description": "As a designer, my process is like riding a wave through its peaks and troughs, representing the deep dives I take to pick up new skills and knowledge, before ascending to achieve impactful outcomes. ",
        "Email": "wangyuwei122@gmail.com",
        "Instagram": "",
        "Behance": "https://www.behance.net/wang_yu_wei",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/yu-wei-wang/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Yen Ching Chiuan",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "WONG HE KAI",
        "PreferredName": "Wong He Kai",
        "Designer Photo 3:4": "",
        "Personal Description": "He Kai is a designer who loves complexity, imaginary problems and new spaces. This currently intersects nicely with design about technology and interaction, where new toys emerge bi-daily, and he tries to reconcile this with his passion for crafts and making.\n\nFor He Kai, making is a game about spinning disparate elements into each other, forming spicy connections into conclusions that can withstand rigorous objective critique. Whether harmonious or dissonant, the goal is a cohesive use experience that approaches inevitability.\n\nHe enjoys shaping materials, experiences, and objects, anything with tight iteration cycles, often blurring all three; He hopes his designs feel natural.",
        "Icon Description": "The blending of 2 convex curves is rarely seen outside of nature, and conveys my core desire as a design student to retain the feeling of the human in my work, no matter how strange or abstract the outcomes. ",
        "Email": "whksoup@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Clement Zheng & Yen Ching Chiuan",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "YE LIN",
        "PreferredName": "Ye Lin",
        "Designer Photo 3:4": "",
        "Personal Description": "Ye Lin is passionate about infusing creativity into our everyday life. To her, design is a constant, subconscious process that everyone engages in, whether we're cooking a meal, selecting the perfect gift, composing a heartfelt letter, or even picking out a piece of furniture for our home. It's in everything we do, and she strives to keep developing her multifaceted skillset and eye for design with every new sight, action or step taken. To incorporate elements of design principles into everyday life by creating and enriching objects or experiences.",
        "Icon Description": "The shape I created resembles both a thumbs up and a high five, representing my belief in the multifaceted nature of design and perception. Just as this form can be seen in two ways, I strive to be a versatile designer adaptable to different perspectives and challenges. ",
        "Email": "yelindesu@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/itsyelin/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "PI",
        "Supervisor": "Christian Boucharenc",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    },
    {
        "FULL NAME": "ZOE KWOK ZIYI",
        "PreferredName": "Zoe Kwok",
        "Designer Photo 3:4": "",
        "Personal Description": "Zoe thrives on connecting unexpected ideas to create new stories\u00e2\u20ac\u201dsometimes, they even solve problems by accident. With a love for graphic design and design research, Zoe dives headfirst into rabbit holes, uncovering insights that shape her work. Her process is research-heavy, followed by rough prototyping until an idea sticks. Writing and sketching blur together in her workflow, along with bouncing ideas off people to refine them further. Armed with a notebook and an instinct for exploration, she approaches design with curiosity and playfulness\u00e2\u20ac\u201dwhether it\u00e2\u20ac\u2122s crafting a concept or literally smacking things until they work. Beyond design, you\u00e2\u20ac\u2122ll find her crafting or wandering solo, collecting new inspirations.",
        "Icon Description": "The shape resembles a tiny crest of a wave. While it is not huge, this wave hopes to push for change where needed, moulding the sand beneath it as it passes along.",
        "Email": "zoekwok02@gmail.com",
        "Instagram": "",
        "Behance": "",
        "Portfolio": "",
        "Portrait": "",
        "LinkedIn": "https://www.linkedin.com/in/zoe-kwok-24a2a3178/",
        "Which of these links you want on your Archive profile": "",
        "Which of these links you want on your Gradsite profile (max 2)": "",
        "Project Title ( 1 Liner)": "",
        "Cluster": "SS",
        "Supervisor": "Alistair Norris",
        "Main Project Picture 16:9": "",
        "Header & Description": "",
        "2nd pic (16:9)": "",
        "3rd Pic (3:4)": "",
        "3 pictures (3:4)": "",
        "Project Title": "",
        "Project Description": "",
        "Video (Youtube/Vimeo)": ""
    }
]

export { DESIGNER_DATA }